---
'on':
  push:

jobs:
  collect_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - uses: octokit/graphql-action@v2.2.23
        id: get_pulls
        with:
          query: |
            query user($login:String!) {
              user(login:$login) {
                pullRequests(last: 100) {
                  edges {
                    node {
                      repository {
                        name
                        owner {
                          login
                        }
                      }
                      title
                      state
                    }
                  }
                }
              }
            }
          login: ${{ github.event.repository.owner.login }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: "echo '${{ steps.get_pulls.outputs.data }}' >> user_info.json"
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: pip install jinja2
      - run: python create_README.py
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: README.md
          retention-days: 1
